name: Scheduled Workflow

on:
  schedule:
    -  cron: '*/1 * * * *'

  workflow_dispatch:

jobs:
  build:
   runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Script
        run: echo "Workflow executed successfully"
